language: java

sudo: required

services:
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2/repository/

install:
  - ./integration-test/integration-test.sh

script:
  - ./integration-test/build.sh
